### ISSUE TITLE
Make this list 'awesome'

### ISSUE THREAD

**Issue by fasterthanlime** [hardpenguin/linux_porting_people#1]
Maybe it'd be good to get this list added to https://github.com/sindresorhus/awesome — and with that, follow their conventions? It certainly looks like an awesome list!

**Comment by hardpenguin** [comment]
Honestly, I just don't feel like it, as I'd rather stay in full charge of the list (and that might mean not following awesome conventions at some point).

**Comment by fasterthanlime** [comment]
Fair enough! Thanks for responding to this.
